[package]
name = "quake3-native-vm"
version = "0.1.0"
authors = ["robo9k <robo@9k.lv>"]

[[example]]
name = "hello"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.36"
lazy_static = "1.0.0"
enum-primitive-derive = "0.1"
num-traits = "0.1"
